window.TEAM_SLUGS = {
  "Alemania": "alemania",
  "Arabia Saudita": "arabia-saudita",
  "Argelia": "argelia",
  "Argentina": "argentina",
  "Australia": "australia",
  "Austria": "austria",
  "Bosnia y Herzegovina": "bosnia-y-herzegovina",
  "Brasil": "brasil",
  "Bélgica": "belgica",
  "Cabo Verde": "cabo-verde",
  "Canadá": "canada",
  "Chequia": "chequia",
  "Colombia": "colombia",
  "Corea del Sur": "corea-del-sur",
  "Costa de Marfil": "costa-de-marfil",
  "Croacia": "croacia",
  "Curazao": "curazao",
  "Ecuador": "ecuador",
  "Egipto": "egipto",
  "Escocia": "escocia",
  "España": "espana",
  "Estados Unidos": "estados-unidos",
  "Francia": "francia",
  "Ghana": "ghana",
  "Haití": "haiti",
  "Inglaterra": "inglaterra",
  "Irak": "irak",
  "Irán": "iran",
  "Japón": "japon",
  "Jordania": "jordania",
  "Marruecos": "marruecos",
  "México": "mexico",
  "Noruega": "noruega",
  "Nueva Zelanda": "nueva-zelanda",
  "Panamá": "panama",
  "Paraguay": "paraguay",
  "Países Bajos": "paises-bajos",
  "Portugal": "portugal",
  "Qatar": "qatar",
  "RD Congo": "rd-congo",
  "Senegal": "senegal",
  "Sudáfrica": "sudafrica",
  "Suecia": "suecia",
  "Suiza": "suiza",
  "Turquía": "turquia",
  "Túnez": "tunez",
  "Uruguay": "uruguay",
  "Uzbekistán": "uzbekistan"
};